/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonIndexRouteImport } from './routes/person/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PersonPersonIdRouteImport } from './routes/person/$personId'
import { Route as PeoplePageRouteImport } from './routes/people/$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonIndexRoute = PersonIndexRouteImport.update({
  id: '/person/',
  path: '/person/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonPersonIdRoute = PersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePageRoute = PeoplePageRouteImport.update({
  id: '/people/$page',
  path: '/people/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/people/$page': typeof PeoplePageRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/people/': typeof PeopleIndexRoute
  '/person/': typeof PersonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/people/$page': typeof PeoplePageRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/people': typeof PeopleIndexRoute
  '/person': typeof PersonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/people/$page': typeof PeoplePageRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/people/': typeof PeopleIndexRoute
  '/person/': typeof PersonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/people/$page'
    | '/person/$personId'
    | '/people/'
    | '/person/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/people/$page' | '/person/$personId' | '/people' | '/person'
  id:
    | '__root__'
    | '/'
    | '/people/$page'
    | '/person/$personId'
    | '/people/'
    | '/person/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeoplePageRoute: typeof PeoplePageRoute
  PersonPersonIdRoute: typeof PersonPersonIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  PersonIndexRoute: typeof PersonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/': {
      id: '/person/'
      path: '/person'
      fullPath: '/person/'
      preLoaderRoute: typeof PersonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$personId': {
      id: '/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof PersonPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$page': {
      id: '/people/$page'
      path: '/people/$page'
      fullPath: '/people/$page'
      preLoaderRoute: typeof PeoplePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeoplePageRoute: PeoplePageRoute,
  PersonPersonIdRoute: PersonPersonIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  PersonIndexRoute: PersonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
